#language: node_js
#node_js:
#- "11"
#addons:
#  chrome: stable
#before_script:
#- npm install -g karma-cli
#- npm install
#- export CHROME_BIN=chromium-browser
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
#script:
#- karma start --single-run
os: osx
language: node_js
sudo: required
addons:
  chrome: stable
before_script:
- npm install -g karma-cli
script:
- karma start --single-run
node_js:
- "11"